version: "3.8"

services:

  db:
    container_name: postgre-db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  broker:
    container_name: redis-be
    image: redis
    ports: 
      - 6379:6379      

  pgadmin:
    container_name: pg-admin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db
  app:
    container_name: p-app
    build: .
    command: bash -c "flask db upgrade && gunicorn --bind 0.0.0.0:${PORT} wsgi:application"
    volumes:
      - .:/d_app
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
      - redis