"""Initial migration.

Revision ID: 79ee45fd3170
Revises: 
Create Date: 2021-08-08 16:59:39.161890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "79ee45fd3170"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "black_listed_token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=500), nullable=False),
        sa.Column("blacklisted_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "popular_podcast",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("podcast_id", sa.Integer(), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("bio", sa.String(length=500), nullable=True),
        sa.Column("profile_img", sa.String(length=35), nullable=False),
        sa.Column("password", sa.String(length=60), nullable=False),
        sa.Column("join_date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "podcast",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("publish_date", sa.String(length=60), nullable=True),
        sa.Column("audio_file", sa.String(length=60), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("cover_img", sa.String(length=60), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("podcast_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["podcast_id"],
            ["podcast.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "view",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.String(length=20), nullable=True),
        sa.Column("podcast_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["podcast_id"],
            ["podcast.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "answer_comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("comment_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("answer_comment")
    op.drop_table("view")
    op.drop_table("comment")
    op.drop_table("podcast")
    op.drop_table("user")
    op.drop_table("popular_podcast")
    op.drop_table("black_listed_token")
    # ### end Alembic commands ###
